language: java
jdk:
 - oraclejdk8

install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install

addons:
   sonarcloud:
       organization: "sweihmws2018-19"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pdev sonar:sonar
  - mvn org.apache.maven.plugins:maven-assembly-plugin:2.6:assembly -DdescriptorId=jar-with-dependencies package


### disabled deployment because of authentication issues with AWS Starter Accounts

#deploy:
#  provider: lambda
#  function_name: "hypershop"
#  region: "us-east-1"
#  role: "arn:aws:iam::711875688686:role/lambda_basic_execution"
#  runtime: "java8"
#  handler_name: "edu.hm.cs.seng.hypershop.HypershopStreamHandler"
